DH-Airline/dh_airline/accounts/urls.py
# April 16, 2020
# Kyle Ear
# Gerardo Pena
from django.urls import include, path
from django.contrib.auth import views as auth_views
from accounts.views import signup_view, account_view

app_name='accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    # call loginview from auth_view  template_name is what we wanna connect to
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/', signup_view, name='signup'),
    path('account/', account_view, name='account'),
]

DH-Airline/dh_airline/cart/urls.py
from django.urls import include, path, re_path
from django.conf.urls import url
from . import views
from .views import (
    add_to_cart,
    order_details,
    CartPage,
)

app_name = 'cart'

urlpatterns = [
    path('', CartPage.as_view(), name='cartpage'),
    path('', views.PaymentPage.as_view(),name='payment'),
    path('add-to-cart/<item_id>/', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="cart_summary"),
    #url(r'^success/$', success, name='purchase_success'),
    #url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    #url(r'^checkout/$', checkout, name='checkout'),
    #url(r'^update-transaction/(?P<token>[-\w]+)/$', update_transaction_records,
    #    name='update_records')
]

DH-Airline/dh_airline/dh_airline/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.HomePage.as_view()),
    path('home/', views.HomePage.as_view(), name='homepage'),
    path('mytrips/', views.MyTripsPage.as_view(), name='reservepage'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('login/', views.LogIn.as_view(), name='login'),
    path('logout/', views.LogOut.as_view(), name='logout'),
    path('book/', include("flights.urls", namespace="book")),
    path('cart/', include("cart.urls", namespace='cartpage')),
    path('checkout/', views.CheckOutPage.as_view(), name = 'checkout'),
    path('confirmation/', views.ConfirmationPage.as_view(), name = 'confirmation'),
    path('mytrips/', views.MyTripsPage.as_view(), name = 'mytrips'),
    path('mytripsconfirmation/', views.MyTripsConfirmation.as_view(), name = 'mytripsconfirmation'),
    path('report/', views.ManagerReport.as_view(), name = 'managerreport')

]

DH-Airline/dh_airline/flights/urls.py
from django.urls import path,re_path
from . import views
from cart.views import add_to_cart

app_name = 'flights'

urlpatterns = [
    path('', views.BookPage.as_view(), name='bookpage'),
    path('s/', views.search, name='search'),
    path('flight/<pk>/', views.FlightDetailView.as_view(), name='detailpage'),
    path('add/<pk>/', views.add_flight, name="add"),
    
]

DH-Airline/dh_airline/templates/base.html
<!--Kyle Ear-->
<!--Jeremy Viray-->
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Flight Hub</title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
      <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@700&display=swap" rel="stylesheet">
      <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
      {% block css_block %}

      {% endblock %}
        <link rel="stylesheet" href="{% static 'css/base.css'%}">
  </head>
  <body>
      <!-- Navbar -->
      <nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
        <!-- container-fluid to make sure navbar spans entire screen -->
        <div class="container-fluid">
          <!-- Brand name and hamburger icon grouped in header -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <!--  Code for the hamburger icon-->
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="{% url 'homepage' %}"><img src="{% static "images/DH_LOGO.png" %}" style="width: 100px; margin-top:15px;"> </a>

           </div> <!-- end header -->

          <!-- Items within hamburger -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <!--Links-->
            <ul class="nav navbar-nav navbar-right">

              <li><a href="{% url 'flights:bookpage' %}">Book</a> </li>
              <li><a href="{% url 'mytrips' %}">My Trips</a> </li>
              <li><a href="{% url 'managerreport' %}">Manager Report</a> </li>

              <li><a href="">Support</a></li>

              <li><a href="{% url 'cart:cartpage' %}">Cart</a></li>


              {% if user.is_authenticated %}

              <!-- add in drop down list links for account settings, profile picture, etc-->
              <li><a href="{% url 'accounts:logout' %}">Log Out</a> </li>
              <li><a href="{% url 'accounts:account' %}">Edit Account</a> </li>

              {% else %}
              <li><a href="{% url 'accounts:login' %}">Log In</a> </li>
              <li><a href="{% url 'accounts:signup' %}">Sign Up</a> </li>
              {% endif %}
            </ul> <!--end list-->
          </div> <!-- end hamburger -->
        </div> <!-- end container-fluid-->

      </nav>

      {% block content %}

      {% endblock %}

      <script
      src="http://code.jquery.com/jquery-3.1.1.js"
      integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
      crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

DH-Airline/dh_airline/templates/bookpage.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/bookpage.css'%}">
<div class="container">
  <form role="search" action='/book/s/'>
      <div class="form-group" method="post">
        <label for="to" style="font-size:18px;">To:</label>
        <input id="bookForm" class="form-control" type="text" name="origin" placeholder="From">
      </div>

      <div class="form-group">
        <label for="from" style="font-size:18px;">From:</label>
        <input id="bookForm" class="form-control" type="text" name="destination" placeholder="To">
      </div>
      <input type="submit">
    </form>
    <h1>{{ DNE }}</h1>
</div>

{% endblock %}

DH-Airline/dh_airline/templates/cartpage.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static "css/cartpage.css" %}"></link>
<div class="content">
  <table class="table table-hover table-bordered text-center">
        <tr class="text-center">
          <th>Date Ordered</th>
          <th>Reference Code</th>
          <th>Item(s)</th>
          <th>Price(s) </th>
        </tr>
        {% for order in my_orders %}
          <tr>
            <td>{{ order.date_ordered }}</td>
            <td>{{ order.ref_code }}</td>
            <td>
            {% for item in order.items.all %}
              {{ item.flights.name }}
            {% endfor %}
            </td>
            <td>${{ order.get_cart_total }}</td>

          </tr>
        {% empty %}
          <tr>
            <td colspan= 4>
              <div class="info">
                <div class="col-sm-4">
                  5/4/2020
                </div>
                <div class="col-sm-4">
                  142352
                </div>
                <div class="two">
                  <div class="col-sm-2">
                    California to Alaska
                  </div>
                </div>
                  <div class="col-sm-2">
                    $350
                  </div>

              </div>
            </td>
          </tr>
        {% endfor %}

        <tr>
          <td colspan=4>
            <a href="{% url 'flights:bookpage' %}" class="btn btn-warning pull-left">
              {% if not order %}Find another Flight{% else %}Add Items to Cart {% endif %}
            </a>
            <a href="{% url 'checkout'%}" class="btn btn-info pull-right">
              Checkout
            </a>
          </td>
        </tr>
      </table>
</div>


{% endblock content %}

DH-Airline/dh_airline/templates/checkout.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/payment.css'%}">
<div class="row">
  <div class="col-75">
    <div class="container">
      <form action="/action_page.php">

        <div class="row">
          <div class="col-50">
            <h3>Billing Address</h3>
            <label for="fname"><i class="fa fa-user"></i> Full Name</label>
            <input type="text" id="fname" name="firstname" placeholder="John M. Doe">
            <label for="email"><i class="fa fa-envelope"></i> Email</label>
            <input type="text" id="email" name="email" placeholder="john@example.com">
            <label for="adr"><i class="fa fa-address-card-o"></i> Address</label>
            <input type="text" id="adr" name="address" placeholder="542 W. 15th Street">
            <label for="city"><i class="fa fa-institution"></i> City</label>
            <input type="text" id="city" name="city" placeholder="New York">

            <div class="row">
              <div class="col-50">
                <label for="state">State</label>
                <input type="text" id="state" name="state" placeholder="NY">
              </div>
              <div class="col-50">
                <label for="zip">Zip</label>
                <input type="text" id="zip" name="zip" placeholder="10001">
              </div>
            </div>
          </div>

          <div class="col-50">
            <h3>Payment</h3>
            <label for="fname">Accepted Cards</label>
            <div class="icon-container">
              <i class="fa fa-cc-visa" style="color:navy;"></i>
              <i class="fa fa-cc-amex" style="color:blue;"></i>
              <i class="fa fa-cc-mastercard" style="color:red;"></i>
              <i class="fa fa-cc-discover" style="color:orange;"></i>
            </div>
            <label for="cname">Name on Card</label>
            <input type="text" id="cname" name="cardname" placeholder="John More Doe">
            <label for="ccnum">Credit card number</label>
            <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
            <label for="expmonth">Exp Month</label>
            <input type="text" id="expmonth" name="expmonth" placeholder="September">

            <div class="row">
              <div class="col-50">
                <label for="expyear">Exp Year</label>
                <input type="text" id="expyear" name="expyear" placeholder="2018">
              </div>
              <div class="col-50">
                <label for="cvv">CVV</label>
                <input type="text" id="cvv" name="cvv" placeholder="352">
              </div>
            </div>
          </div>

        </div>
        <label>
          <input type="checkbox" checked="checked" name="sameadr"> Shipping address same as billing
        </label>
      </form>
    </div>
  </div>

  <div class="col-25">
    <div class="container">
      <h4>Cart
        <span class="price" style="color:black">
          <i class="fa fa-shopping-cart"></i>
          <b>4</b>
        </span>
      </h4>
      <p>California to Alaska. 2 Stops <span class="price">$350</span></p>

      <hr>
      <p>Total <span class="price" style="color:black"><b>$362.15</b></span></p>
    </div>
    <a href="{% url 'confirmation'%}" id="checkout" class="btn btn-info pull-right">
      Checkout
    </a>
  </div>
</div>

DH-Airline/dh_airline/templates/confirmation.html
{%load static%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/confirmation.css'%}">
  </head>
  <body>
    <div class="content">
      <h1>Thank you for your purchase!</h1>
      <p>your order confirmation is 938472312</p>
      <p>A reciept has been sent to your email with your order confirmation. Please check your email and contact us if any questions or concerns are present </p>
    </div>
  </body>
      <a class="navbar-brand" href="{% url 'homepage' %}">Return to Home Page </a>
</html>

DH-Airline/dh_airline/templates/homepage.html
{%extends "base.html"%}
{% load static %}
{% block css_block %}
  <link rel="stylesheet" href="{% static "css/homepage.css" %}"></link>

{% endblock %}
{% block content %}
<!-- Booking jumbotron -->
      <!-- Booking jumbotron -->
      <div class="container" id="bookContainer">

        <div class="row">
            <div class="col col-lg-6 col-xs-12">
              <div class="jumbotron" id="bookJumbo">
                  Welcome to Da Hub! 
              </div> <!--end jumbotron-->
            </div> <!--end col-->
          </div> <!--end row-->

        </div> <!--end bookContainer-->


  <div class="" style="background-color: white; margin-top: 50px; color:black;">
    <div class="">

    </div>
    <h1 style="text-align: center;"><strong>You're the reason we fly!</strong></h1> <br>
    <h2 id="safety" style="text-align:center;">Our safety commitment</h2> <br> <br> <br>

    <div class="aboutus">
      <p class="aboutusparagraph">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p class="aboutusparagraph">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p class="aboutusparagraph">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

    </div>





  </div>

  <div class="container" id="flyWithUs">
    <div class="row">

      <!-- Text -->
      <div class="col col-xs-12 col-sm-6">
        <h3><strong>Fly With Us!</strong></h3><br>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <a href="#">Link</a>
      </div>

      <!-- Image -->
      <div class="col col-xs-12 col-lg-6 ">
      <img class="" id="reachHigh" src="https://www.fullerton.edu/ecs/env/_resources/images/Titans-Reach-Higher.jpg" alt="">
      </div>
  </div>
</div>


<!-- Footer -->
<footer class="footer">

  <div style="background-color: ">
    <div class="container">

      <!-- Grid row-->
      <div class="row py-4 d-flex align-items-center">

        <!-- Grid column -->

        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-6 col-lg-7 text-center text-md-right">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f white-text mr-4"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter white-text mr-4"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic">
            <i class="fab fa-google-plus-g white-text mr-4"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in white-text mr-4"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram white-text"> </i>
          </a>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row-->

    </div>
  </div>

  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5">

    <!-- Grid row -->
    <div class="row mt-3">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
        <div class="footertext">
          <!-- Content -->
          <h6 class="text-uppercase font-weight-bold">Da Hub</h6>
          <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px; ">
          <p>Creating an airline website where the user can log in, book flights, pay, etc.</p>
        </div>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <div class="footertext">
            <h6 class="text-uppercase font-weight-bold">Group</h6>

          <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            Kyle Ear Gerardo Pena
          </p>
          <p>
            Brandon Le Allen Rivas
          </p>
          <p>
            Jeremy Viray
          </p>
      </div>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <div class="footertext">
          <h6 class="text-uppercase font-weight-bold">Languages Used</h6>

        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          Django
        </p>
        <p>
          Bootstrap html
        </p>
        <p>
          Css
        </p>
        </div>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <!-- Links -->
      <div class="footertext">
        <h6 class="text-uppercase font-weight-bold">Contact</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <i class="fas fa-home mr-3"></i> Da hub</p>
        <p>
          <i class="fas fa-envelope mr-3"></i> Dahub@csu.fullerton.edu</p>
        <p>
          <i class="fas fa-phone mr-3"></i> Da hub university baby</p>


      </div>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->

  <!-- Copyright -->

</footer>
<!-- Footer -->
{% endblock %}

DH-Airline/dh_airline/templates/logout.html
{extends "base.html"}
{% block body_block %}

{% endblock %}

DH-Airline/dh_airline/templates/managerreport.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static "css/manager.css" %}"></link>
{% for flight in flights %}
          <h2><li>{{ flight}}</li></h2>
        {% endfor %}
</body>
</html>
{% endblock content %}

DH-Airline/dh_airline/templates/myTrips.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/myTrips.css'%}">
<body>
  <div class="content">
    <div class="container" id="myTripsContainer">

        <div class="row">
            <div class="col col-lg-6 col-xs-12">
                <div class= id="myTripsJumbo">
                    <h2 id="myTripsHeader"> My Trips </h2>
                    <form>
                        <div class="container">
                            <!-- <div><label><b>Confirmantion Number</b></label> -->
                            <input type="text" id="confirmantion" placeholder="Confirmantion Number*" name="uname"
                                required>

                            <div class="">
                              <button type="Submit"  class="btn btn-info" name="button"><a href="{% url 'mytripsconfirmation' %}"">Search</a></button>
                            </div>
                            <!-- <input type="checkbox" checked="checked"> Remember me -->
                        </div>
                    </form>
                </div>
                <!--end jumbotron-->
            </div>
            <!--end col-->
        </div>
        <!--end row-->

    </div>
    <!--end myTripsContainer-->
  </div>

    <script src="myTrips.js"></script>
    <script src="http://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
        crossorigin="anonymous"></script> <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
    </script>


</body>
{% endblock %}

DH-Airline/dh_airline/templates/myTripsConfirmation.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static "css/cartpage.css" %}"></link>
<div class="content">
  <table class="table table-hover table-bordered text-center">
        <tr class="text-center">
          <th>Date Ordered</th>
          <th>Reference Code</th>
          <th>Item(s)</th>
          <th>Price(s) </th>
        </tr>
        {% for order in my_orders %}
          <tr>
            <td>{{ order.date_ordered }}</td>
            <td>{{ order.ref_code }}</td>
            <td>
            {% for item in order.items.all %}
              {{ item.flights.name }}
            {% endfor %}
            </td>
            <td>${{ order.get_cart_total }}</td>

          </tr>
        {% empty %}
          <tr>
            <td colspan= 4>
              <div class="info">
                <div class="col-sm-4">
                  5/4/2020
                </div>
                <div class="col-sm-4">
                  142352
                </div>
                <div class="two">
                  <div class="col-sm-2">
                    California to Alaska
                  </div>
                </div>
                  <div class="col-sm-2">
                    $350
                  </div>

              </div>
            </td>
          </tr>
        {% endfor %}

        <tr>

        </tr>
      </table>
</div>


{% endblock content %}